import{a as L,S as q,i as a}from"./assets/vendor-mdVVRe9K.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="46153478-1b8179550e9312780d25c3b1d",$="https://pixabay.com/api/";async function f(t,o=1){const s=`${$}?key=${E}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`;try{const n=await L.get(s),{hits:e,totalHits:r}=n.data;return{images:e,totalHits:r}}catch(n){throw console.error("Error fetching images:",n),n}}function m(t){const o=document.querySelector(".gallery"),s=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:l,views:g,comments:b,downloads:v})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${n}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${l}</p>
          <p><b>Views</b> ${g}</p>
          <p><b>Comments</b> ${b}</p>
          <p><b>Downloads</b> ${v}</p>
        </div>
      </div>`).join("");o.insertAdjacentHTML("beforeend",s)}function w(){const t=document.querySelector(".gallery");t.innerHTML=""}const S=document.querySelector("#search-form"),c=document.querySelector("#loader"),u=document.querySelector("#load-more-btn");let d=1,p="",y=0,i=0;const h=new q(".gallery a",{captionsData:"alt",captionDelay:250,close:!0});S.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.searchQuery.value.trim();if(o===""){a.error({title:"Error",message:"Please enter a search query"});return}c.style.display="block",d=1,p=o,w(),u.style.display="none",i=0;try{const{images:s,totalHits:n}=await f(o,d);if(y=n,s.length===0){a.error({title:"No results",message:"No images found for your search query"});return}m(s),h.refresh(),i+=s.length,i<y?u.style.display="block":a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}catch{a.error({title:"Error",message:"Failed to fetch images"})}finally{c.style.display="none"}});u.addEventListener("click",async()=>{d+=1,c.style.display="block";try{const{images:t}=await f(p,d);m(t),h.refresh(),i+=t.length,i>=y?(a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}),u.style.display="none"):P()}catch{a.error({title:"Error",message:"Failed to fetch images"})}finally{c.style.display="none"}});function P(){setTimeout(()=>{const t=document.querySelector(".photo-card");if(t){const{height:o}=t.getBoundingClientRect(),s=o*4;window.scrollBy({top:s,behavior:"smooth"})}},100)}
//# sourceMappingURL=index.js.map
