import{a as b,S as L,i}from"./assets/vendor-mdVVRe9K.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="46153478-1b8179550e9312780d25c3b1d",q="https://pixabay.com/api/";async function u(t,o=1){const s=`${q}?key=${$}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`;try{return(await b.get(s)).data.hits}catch(a){throw console.error("Error fetching images:",a),a}}function d(t){const o=document.querySelector(".gallery"),s=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:n,views:m,comments:g,downloads:h})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${a}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${n}</p>
          <p><b>Views</b> ${m}</p>
          <p><b>Comments</b> ${g}</p>
          <p><b>Downloads</b> ${h}</p>
        </div>
      </div>`).join("");o.insertAdjacentHTML("beforeend",s)}function v(){const t=document.querySelector(".gallery");t.innerHTML=""}const E=document.querySelector("#search-form"),c=document.querySelector("#loader"),y=new L(".gallery a",{captionsData:"alt",captionDelay:250,close:!0});let l=1,f="";E.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.searchQuery.value.trim();if(o===""){i.error({title:"Error",message:"Please enter a search query"});return}c.style.display="block",l=1,f=o,v();try{const s=await u(o,l);if(s.length===0){i.error({title:"No results",message:"No images found for your search query"});return}d(s),y.refresh(),p.style.display="block"}catch{i.error({title:"Error",message:"Failed to fetch images"})}finally{c.style.display="none"}});const p=document.querySelector("#load-more-btn");p.addEventListener("click",async()=>{l+=1,c.style.display="block";try{const t=await u(f,l);d(t),y.refresh()}catch{i.error({title:"Error",message:"Failed to fetch images"})}finally{c.style.display="none"}});
//# sourceMappingURL=index.js.map
