import{a as q,S as v,i as l}from"./assets/vendor-mdVVRe9K.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const $="46153478-1b8179550e9312780d25c3b1d",w="https://pixabay.com/api/";async function f(t,r=1){const s=`${w}?key=${$}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${r}`;try{const n=await q.get(s),{hits:e,totalHits:o}=n.data;return{images:e,totalHits:o}}catch(n){throw console.error("Error fetching images:",n),n}}function m(t){const r=document.querySelector(".gallery"),s=t.map(({webformatURL:n,largeImageURL:e,tags:o,likes:a,views:h,comments:b,downloads:L})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${n}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${a}</p>
          <p><b>Views</b> ${h}</p>
          <p><b>Comments</b> ${b}</p>
          <p><b>Downloads</b> ${L}</p>
        </div>
      </div>`).join("");r.insertAdjacentHTML("beforeend",s)}function E(){const t=document.querySelector(".gallery");t.innerHTML=""}const S=document.querySelector("#search-form"),i=document.querySelector("#loader"),c=document.querySelector("#load-more-btn"),p=new v(".gallery a",{captionsData:"alt",captionDelay:250,close:!0});let u=1,g="",d=0,y=0;S.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.searchQuery.value.trim();if(r===""){l.error({title:"Error",message:"Please enter a search query"});return}i.style.display="block",u=1,g=r,E();try{const{images:s,totalHits:n}=await f(r,u);if(d=n,y=s.length,y===0){l.error({title:"No results",message:"No images found for your search query"}),c.style.display="none";return}m(s),p.refresh(),c.style.display=d>15?"block":"none"}catch{l.error({title:"Error",message:"Failed to fetch images"})}finally{i.style.display="none"}});c.addEventListener("click",async()=>{u+=1,i.style.display="block";try{const{images:t,totalHits:r}=await f(g,u);if(d=r,y+=t.length,t.length===0||y>=d){l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none";return}m(t),p.refresh(),H()}catch{l.error({title:"Error",message:"Failed to fetch images"})}finally{i.style.display="none"}});function H(){const t=document.querySelector(".photo-card");if(t){const{height:r}=t.getBoundingClientRect(),s=r*4;window.scrollBy({top:s,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
